name: Bug report
description: Create a bug report to help us improve this project
title: "[Bug] "
assignees:
  - sn4k3
body:
  - type: markdown
    attributes:
      value: |
        Before filing, please check if the issue already exists (either open or closed) by using the search bar on the [issues page](https://github.com/sn4k3/NetSonar/issues?q=). If it does, comment there. Even if it's closed, we can reopen it based on your comment.
  - type: textarea
    id: system
    attributes:
      label: System
      placeholder: |
        1. Go to "About (F1)"
        2. Click on "Copy information"
        3. Paste that infomation here
      render: Text
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is. Please, enclose a screenshot whenever possible (even when you think the description is clear). What did you expect to happen?
      placeholder: |
        What is the problem?
        What did you expect?
        You paste or drop screenshots here
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Files
      description: "Zip all related files and paste or drop them here. If they are too large please use a file host service and paste the link(s) here, eg: [wetransfer.com](https://wetransfer.com)"
      placeholder: |
        - You paste or drop file(s) here
        - You paste or drop link(s) here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Overview before submit
        1. Use descriptive and complete title!
        2. Review all information and make sure it's clear and complete.
        3. Take full window screenshots, don't cut information even if you think it's unnecessary!
        4. Note that the information and files posted here will be public.

        # [![NetSonar](https://github.com/sn4k3/NetSonar/raw/main/media/NetSonar-32.png)](#) Thank's you!